### ISSUE TITLE
Pathmuncher Doesn't Work with Basic Test with New Character

### ISSUE THREAD

**Issue by jayleew** [MrPrimate/pathmuncher#15]
Importing JSON ID: 179798
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Shield Block. This might not be an issue, but might indicate feature duplication. {document: {…}, parent: {…}}
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:612
#addGrantedRules @ Pathmuncher.js:927
await in #addGrantedRules (async)
#addGrantedItems @ Pathmuncher.js:1039
#addGrantedItems @ Pathmuncher.js:1033
await in #addGrantedItems (async)
#processGenericCompendiumLookup @ Pathmuncher.js:479
await in #processGenericCompendiumLookup (async)
processCharacter @ Pathmuncher.js:2030
await in processCharacter (async)
_updateObject @ PathmuncherImporter.js:104
await in _updateObject (async)
_onSubmit @ foundry.js:5916
commons.js:6946 Foundry VTT | Created Actor with id [B1FB59P5uPAYlTjL]
commons.js:6946 Foundry VTT | Created 3 Item documents with ids: [ZTd4pjcORKKsD27Y,TjJZjxDoDZ5eQSUp,VLFoaFLw7upnQxVt] in parent Actor [B1FB59P5uPAYlTjL]
commons.js:6946 Foundry VTT | Deleted Actor with id [B1FB59P5uPAYlTjL]
foundry.js:5919 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at #generateEquipmentItems (Pathmuncher.js:1336:1)
    at async #processEquipment (Pathmuncher.js:1845:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2043:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:104:1)
    at async PathmuncherImporter._onSubmit (foundry.js:5916:7)

**Comment by MrPrimate** [comment]
The bug report template asks for a number of things which you haven't included which I will need to reproduce and understand the bug:

**Environment:**
 - Browser [e.g. chrome]
 - Foundry Version [e.g. 10.288]
 - Pathfinder System Version [e.g 2.0.3]
 - Module Version [e.g 3.1.21]
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)

**Additional context**
Add any other context about the problem here.

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
It might also be that this character was exported with an older version of Pathbuilder and the JSON is not longer accepted by Pathbuilder. Please try exporting the JSON again.
