### ISSUE TITLE
No longer works on latest Foundry PF2e game version

### ISSUE THREAD

**Issue by CScarlett** [MrPrimate/pathmuncher#26]
**Describe the bug**
Muncher hangs almost immediately after starting. Throws this error in console:

Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:3339:42)
    at Pathmuncher.js:593:1
    at Array.find (<anonymous>)
    at #parsedFeatureMatch (Pathmuncher.js:576:1)
    at #findAllFeatureMatch (Pathmuncher.js:631:1)
    at #createGrantedItem (Pathmuncher.js:652:1)
    at #addGrantedItems (Pathmuncher.js:1176:1)
    at async #processGenericCompendiumLookup (Pathmuncher.js:530:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2339:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:104:1)
_onSubmit @ foundry.js:6629

**To Reproduce**
Import a character on latest Foundry PF2e game system update

**Environment:**
 - Browser: Firefox, Chrome
 - Foundry Version 11.315
 - Pathfinder System Version 5.9.0
 - Module Version 0.10.1
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
 - https://pathbuilder2e.com/launch.html?build=590024

**Comment by MrPrimate** [comment]
Resolved in v0.11.0, out now.
