### ISSUE TITLE
Basic Attributes not bring imported.

### ISSUE THREAD

**Issue by Rayquaza1090** [MrPrimate/pathmuncher#29]
**Describe the bug**
Thanks to your most recent update, I am now able to import, but I run into an issue where the stats imported are 0 and cannot be modified when I click on the edit button.

This is also something I'm not sure is related to it- but whenever I export a character from the Pathbuilder site now, I always get the same number "202930". I attempted importing the unique JSON code associated with the character instead of the code, but that didn't seem to fix the issue.

**To Reproduce**
1. Disabled all modules.
2. Go to https://pathbuilder2e.com/launch.html?build=583906
3. Click on Export JSON and copy the number (202930)
4. Import via Pathmuncher Module in Foundry VTT
5. See all stats at 0.

**Expected behavior**
The stats are supposed to be what is reflected on the web page I specified.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
(https://i.imgur.com/Q69nkSE.png)
The console says virtually nothing. This is the first time I've seen the red error at the bottom, so I can't say for certain that it's related. 

**Environment:**
 - Browser Chrome
 - Foundry Version 11 315 Stable
 - Pathfinder System Version 5.9.1
 - Module Version 0.11.0
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

Literally as I refreshed the main page I saw there was a 0.11.1 Update so I'm going to test that and if it fixes the problem I'll delete this thread. I still have a problem with importing some of the runes on weapons so I may have to harass the devs about that. Thanks for taking the time to read and maintain these.

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
https://pathbuilder2e.com/launch.html?build=583906
 - Details of any errors in the browser console (press F12).

Foundry VTT | Created Actor with id [V5yoSRsOqs7TyxDI]
commons.js:8807 Foundry VTT | Created 5 Item documents with ids: [mox76wPuzCQ7ZRI2,b4c15YInSLHa30jH,d2Pd92SwtDbmAyUX,4FqggAT5ObFAYL02,3Xo6VVkyVvx9srvk] in parent Actor [V5yoSRsOqs7TyxDI]
commons.js:8807 Foundry VTT | Deleted Actor with id [V5yoSRsOqs7TyxDI]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Hunter's Edge. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
commons.js:8807 Foundry VTT | Created Actor with id [WXd0DUekSdIlvdyF]
commons.js:8807 Foundry VTT | Created 10 Item documents in parent Actor [WXd0DUekSdIlvdyF]
foundry.js:16235 Foundry VTT | Constructed index of pf2e.ancestryfeatures Compendium containing 39 entries
foundry.js:16235 Foundry VTT | Constructed index of pf2e.classfeatures Compendium containing 562 entries
foundry.js:16235 Foundry VTT | Constructed index of pf2e.feats-srd Compendium containing 4196 entries
foundry.js:16235 Foundry VTT | Constructed index of pf2e.boons-and-curses Compendium containing 240 entries
foundry.js:16235 Foundry VTT | Constructed index of pf2e.campaign-effects Compendium containing 30 entries
foundry.js:16235 Foundry VTT | Constructed index of pf2e.pathfinder-society-boons Compendium containing 132 entries
commons.js:8807 Foundry VTT | Deleted Actor with id [WXd0DUekSdIlvdyF]
commons.js:8807 Foundry VTT | Created Actor with id [MLqKAEhQe6UOmA3r]
commons.js:8807 Foundry VTT | Created 11 Item documents in parent Actor [MLqKAEhQe6UOmA3r]
commons.js:8807 Foundry VTT | Deleted Actor with id [MLqKAEhQe6UOmA3r]
commons.js:8807 Foundry VTT | Created Actor with id [MBdDUEvTChTtqxUJ]
commons.js:8807 Foundry VTT | Created 12 Item documents in parent Actor [MBdDUEvTChTtqxUJ]
commons.js:8807 Foundry VTT | Deleted Actor with id [MBdDUEvTChTtqxUJ]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Will Expertise. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Trackless Journey. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Ranger Weapon Expertise. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
foundry.js:16235 Foundry VTT | Constructed index of pf2e.spells-srd Compendium containing 1539 entries
commons.js:8807 Foundry VTT | Created Item with id [mox76wPuzCQ7ZRI2] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [b4c15YInSLHa30jH] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [d2Pd92SwtDbmAyUX] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [dcYKJyjEd7Y3JiDV] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [uRyasID9xYEStiDt] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created 2 Item documents with ids: [8QpAgrZLlrHO8mJi,gOnwd1l3g7Y4zvi5] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [4FqggAT5ObFAYL02] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [3Xo6VVkyVvx9srvk] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [tcgJgnBgSFATfCsd] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [7ujpa5RfKApL4rqx] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [GQR08HTd9dgntE59] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [ZJX7Zhajf0IbJpKA] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [rI2d0PVnfKx3F8tU] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [sptPjIZvhlo9cHSr] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [svggOC8yR1eY8Wcs] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [Lzz2YoX3XnXbZ16Q] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [B2t45jo0b1k0jygE] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [hZZu0DmTK3UJEEvx] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [Aq3L3vcFBB9uZcaI] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [qu5dJ0yJclVF2ngu] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [uFLgBkk0IG3mQ1z4] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [XHtW2Gb6sPmGQe5p] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [c3cEV1ipMM2JEyek] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [zeWu1OwNsZgKtiwK] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [fmqXNxQ359W69Pd4] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [DElGgSUnEb60CaXn] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [cxPpL0Q2EaXqdEKT] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [UGj44Y7Hzdq0PSai] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created 2 Item documents with ids: [smh3utS7pt8cN28m,RpXce691up1mnBdG] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created 4 Item documents with ids: [ZqeIUa2D4WMMecS0,DjHa2xuhpj3mQ2Tq,gC22qttkhUS4F5pK,8j6UbC1D8OF4H9Ef] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created Item with id [66d6HblWqGvYFhnh] in parent Actor [xR5bJ6LOb9gr3hUG]
commons.js:8807 Foundry VTT | Created 4 Item documents with ids: [nJJ506v2Ksvd7VFW,9A98mPkAVf8EAyGM,oZPSHLYT9ZzGItjQ,4J97h4en1YjptUCL] in parent Actor [xR5bJ6LOb9gr3hUG]
foundry.js:68326 Import completed with some notes.
fetch @ foundry.js:68326
foundry.js:5802 Foundry VTT | Rendering Dialog
13foundry.js:6310 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at PathmuncherImporter.setPosition (foundry.js:6310:27)
    at Draggable._onDragMouseMove (foundry.js:65481:14)
    at handlers.dragMove (foundry.js:65418:59)

**Comment by Rayquaza1090** [comment]
Update resolved issue.
