### ISSUE TITLE
When trying to import character it hangs at 'Cooking (Armor)...'

### ISSUE THREAD

**Issue by JKFWEB** [MrPrimate/pathmuncher#33]
**Describe the bug**
When importing one of my players characters it never finishes and displays 'Cooking (Armor)...'

**To Reproduce**
1. Create a new actor
2. Open Actor
3. Click on Pathmuncher
4. Type in ID number of 223750
5. Click the Import button
6. It's starts processing but never completes

**Expected behavior**
The import should create a character with all of the details from Pathbuilder.

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/73962543/28cb54f5-ff21-48b9-9731-d58026b1a985)

**Environment:**
 - Chrome, and Edge browser
 - Foundry Version [Version 11 Stable, Build 315]
 - Pathfinder System Version [5.10.5]
 - Pathmuncher [0.11.5]
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
Console Errors below:

pathmuncher | ERR > Unable to match Wand of Mercy (1st-Level Spell) Object

logger.js:60  pathmuncher | ERR > Unable to match Wand of Mercy (2nd-Level Spell) Object

logger.js:60  pathmuncher | ERR > Unable to match weapon item Shield Bash Object

foundry.js:6629  TypeError: Cannot set properties of undefined (setting 'value')
    at Pathmuncher.applyRunes (Pathmuncher.js:1616:1)
    at #generateArmorItems (Pathmuncher.js:1709:1)
    at async #processEquipment (Pathmuncher.js:2152:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2352:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:104:1)
    at async PathmuncherImporter._onSubmit (foundry.js:6626:7)

**Comment by JKFWEB** [comment]
Additionally the other two characters I imported seemed to work fine, it's specifically this character that fails.

**Comment by MrPrimate** [comment]
- In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.

**Comment by PersonalDaemon** [comment]
I've had the same issue with some characters hanging at cooking armor, but not all. I unsuccessfully tried a couple 'fixes' like removing dual class, 3rd party stuff, and the 'custom' armor.

https://pathbuilder2e.com/launch.html?build=609141 link to character with known hang

**Comment by JKFWEB** [comment]
> * In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.

https://pathbuilder2e.com/launch.html?build=609593

Sorry i had to wait for the user to get back to me with the link you requested.

**Comment by MrPrimate** [comment]
> > * In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
> 
> https://pathbuilder2e.com/launch.html?build=609593
> 
> Sorry i had to wait for the user to get back to me with the link you requested.

Can you try with the latest version as well please

**Comment by JKFWEB** [comment]
> > > * In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
> > 
> > 
> > https://pathbuilder2e.com/launch.html?build=609593
> > Sorry i had to wait for the user to get back to me with the link you requested.
> 
> Can you try with the latest version as well please

I just got a chance to test and the character imported correctly now!  Thanks Jack!
